misc:
    humanTimestamp: True
    test_webserver: False
    do_graphics: True
    loglevel: 'DEBUG'  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    
Timers:
    SystemMonitorSleep: 10
    _ETH_MonitorSleep: 10
    _SDX_MonitorSleep: 10
    _CPU_MonitorSleep: 10
    getWeatherInterval: 900
    mainloop_sleep: 150

pathes:
    DATA: '/data'                 # not used yet
    LOG: '/log'
    RRD: '/rrd'
    YML: '/yml'
    PNG: '/png'
    ARCH: '/archiv'
    SCENE: '/Scenes'
    PROG: '/prog'
    HTML: '/html'
    IPAdr: '/IPAdr'
    REG: '/yml/shelly_registry.yml'

DeSeTask:
    Linux:
    #- ['./UpdMemoryRrd.sh', 1]
    #- ['./UpdLoadAvgRrd.sh', 1]
    #- ['./UpdNetworkRrd.sh', 1]
    #- ['./UpdCoreTempRrd.sh', 1]
    #- ['./UpdDiskTraf.sh', 1]
    #- ['./MakeAllGraphs.sh', 20]

    Darwin:
    #- ['/Users/ralphfollrichs/Projects/dabo/progs/UpdAllMac.sh', 5]
    - ['/Users/ralphfollrichs/Projects/dabo/progs/allMac.sh', 60]

    Windows:
    - ['/Users/ralphfollrichs/Projects/dabo/progs/UpdAll.sh', 1]
    - ['/Users/ralphfollrichs/Projects/dabo/progs/all.sh', 1800]

Communication:
    DevServerName: 'Server64.local'    
    DevServerPort: 8080
    DaBoServerPort: 8088

DevServer:
    Timers:
        MonitoringSleep: 1

files:
    DATASTORE_YML: 'datastore.yml'
    DIAGRAMS_YML: 'diagrams.yml'

suffixes:
    log: # '-%Y_%m_%d__%H-%M-%S'     #date and time
         '-%Y_%m_%d'                #date only
         #''                         # hostname only
    data: '-%Y_%m_%d__%H-%M-%S'     #date and time
          #'-%Y_%m_%d'               #date only
          #''                        #without date and time

debug:
    datefmt: '%d.%m.%Y %H:%M:%S'      # normal
    #datefmt: '%d.%m.%Y %H:%M:%S.%s'   # fine (with ms)
    hirestime: False                    # time resolution in data logs (true=ms, false=s)
    humanTimestamp: True
    logYML: True                      #put the yml-file into the log
    verbose: True
    Mailing: True

devices:
    
archive:
